
[[functions]]
name = "analyze-web-content"
verify_jwt = false

[[functions]]
name = "brave-search"
verify_jwt = false

[[functions]]
name = "deep-research"
verify_jwt = false

[[functions]]
name = "evaluate-qa-final"
verify_jwt = false

[[functions]]
name = "evaluate-qa-pair"
verify_jwt = false

[[functions]]
name = "execute-market-order"
verify_jwt = false

[[functions]]
name = "extract-research-insights"
verify_jwt = false

[[functions]]
name = "generate-qa-tree"
verify_jwt = false

[[functions]]
name = "generate-queries"
verify_jwt = false

[[functions]]
name = "get-orderbook"
verify_jwt = false

[[functions]]
name = "get-top-movers"
verify_jwt = false

[[functions]]
name = "market-analysis"
verify_jwt = false

[[functions]]
name = "polymarket-ws"
verify_jwt = false

[[functions]]
name = "price-history"
verify_jwt = false

[[functions]]
name = "search-markets"
verify_jwt = false

[[functions]]
name = "web-research"
verify_jwt = false

[[functions]]
name = "web-scrape"
verify_jwt = false
