
project_id = "lfmkoismabbhujycnqpn"

[functions.polymarket-stream]
verify_jwt = false

[functions.get-orderbook]
verify_jwt = false

[functions.market-analysis]
verify_jwt = false

[functions.analyze-web-content]
verify_jwt = false

[functions.brave-search]
verify_jwt = false

[functions.web-research]
verify_jwt = false

[functions.extract-research-insights]
verify_jwt = false

[functions.orderbook-stream]
verify_jwt = false
