
project_id = "lfmkoismabbhujycnqpn"

# Define functions as an array of tables (using double brackets)
[[functions]]
name = "market-analysis"
verify_jwt = false

[[functions]]
name = "analyze-web-content"
verify_jwt = false

[[functions]]
name = "brave-search"
verify_jwt = false

[[functions]]
name = "web-research"
verify_jwt = false

[[functions]]
name = "extract-research-insights"
verify_jwt = false

[[functions]]
name = "get-orderbook"
verify_jwt = false

[[functions]]
name = "polymarket-stream"
verify_jwt = false
