
project_id = "lfmkoismabbhujycnqpn"

[functions.brave-search]
verify_jwt = false

[functions.web-scrape]
verify_jwt = false

[functions.deep-research]
verify_jwt = false

[functions.analyze-web-content]
verify_jwt = false

[functions.extract-research-insights]
verify_jwt = false

[functions.get-top-movers]
verify_jwt = false

[functions.search-markets]
verify_jwt = false

[functions.polymarket-ws]
verify_jwt = false

[functions.generate-queries]
verify_jwt = false

[functions.get-orderbook]
verify_jwt = false

[functions.market-analysis]
verify_jwt = false

[functions.execute-market-order]
verify_jwt = false

[functions.price-history]
verify_jwt = false

[functions.evaluate-qa-pair]
verify_jwt = false

[functions.generate-qa-tree]
verify_jwt = false
