
project_id = "lfmkoismabbhujycnqpn"

# Define functions with the correct format using [functions.<function-name>]
[functions.market-analysis]
verify_jwt = false

[functions.analyze-web-content]
verify_jwt = false

[functions.brave-search]
verify_jwt = false

[functions.web-scrape]
verify_jwt = false

[functions.web-research]
verify_jwt = false

[functions.extract-research-insights]
verify_jwt = false

[functions.generate-qa-tree]
verify_jwt = false

[functions.evaluate-qa-pair]
verify_jwt = false

[functions.evaluate-qa-final]
verify_jwt = false

[functions.get-orderbook]
verify_jwt = false

[functions.polymarket-ws]
verify_jwt = false

[functions.create-research-job]
verify_jwt = false

[functions.generate-queries]
verify_jwt = false
